<Project>
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SolutionDir>$(MSBuildThisFileDirectory)</SolutionDir>
    <DebugType>embedded</DebugType>
    <RootOutputPath>$(MSBuildThisFileDirectory)</RootOutputPath>
    <PublishDir>$(RootOutputPath)\bin</PublishDir>
  </PropertyGroup>
  <ItemGroup>
    <GlobalAnalyzerConfigFiles Include="$(SolutionDir)\.analyzerconfig" />
  </ItemGroup>
</Project>
